---
# file: roles/nginx/tasks/main.yml

- name: Install Nginx repo
  shell: rpm -Uvh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  ignore_errors: yes
  tags:
    - monitor

- name: Install Nginx
  yum: name=nginx state=latest
  tags:
    - monitor

- name: copy nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  tags:
    - monitor

- name: start nginx
  service: name=nginx enabled=yes state=started
  tags:
    - monitor


