---
# file: roles/spark/tasks/main.yml

- name: create spark directory
  file: path={{ item }} state=directory
  with_items: spark.location
  tags:
    - spark
    - slaves

- name: copy spark
  copy: src=spark-{{ spark.version }}-bin-cdh4.tgz dest=/tmp/spark-{{ spark.version }}-bin-cdh4.tgz
  tags:
    - spark
    - slaves

- name: download Spark
  shell: chdir=/tmp tar zxvf /tmp/spark-{{ spark.version }}-bin-cdh4.tgz && yes | cp -rf /tmp/spark-{{ spark.version }}-bin-cdh4/* {{ spark.location }}
  tags:
    - spark
    - slaves

- name: copy spark-env.sh
  template: src=spark-env.sh dest={{ spark.location }}/conf/spark-env.sh
  tags:
    - spark
    - slaves
