---
# file: roles/elasticsearch/tasks/main.yml

- name: install Elasticsearch
  shell: creates=/usr/share/elasticsearch/bin/elasticsearch chdir=/tmp wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.2.noarch.rpm && rpm -Uvh /tmp/elasticsearch-1.3.2.noarch.rpm
  tags:
    - elasticsearch
    - slaves

- name: create default configuration
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  tags: elasticsearch  

- name: make sure Elasticsearch is enabled and started
  service: name=elasticsearch enabled=yes state=started
  tags:
    - elasticsearch
    - slaves
  notify:
    - restart elasticsearch

- name: install plugin head
  command: chdir=/usr/share/elasticsearch/bin ./plugin -install mobz/elasticsearch-head
  tags:
    - elasticsearch
    - slaves
